# Generated by Django 5.0.1 on 2024-01-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
