# Generated by Django 5.0.1 on 2024-01-19 04:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0003_alter_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="sub_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="blog",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("dfae5ea8-b835-408c-bd45-8ccd724b4726"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
