# Generated by Django 5.0.1 on 2024-01-19 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0004_alter_blog_sub_title_alter_blog_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="sub_title",
            field=models.CharField(default="Sample", max_length=300),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(default="Sample", max_length=200),
        ),
        migrations.AlterField(
            model_name="blog",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("82dcf1a1-cf44-4eb8-b725-9e51c233bfef"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
