# Generated by Django 5.0.1 on 2024-01-19 04:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0005_alter_blog_sub_title_alter_blog_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="sub_title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="blog",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="blog",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
