# Generated by Django 5.0.1 on 2024-01-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0007_alter_blog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                default="blogs/images/default-blog.png", upload_to="blogs/images"
            ),
        ),
    ]
